name: Quality Gate

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # If set in repo secrets, enables OWASP Dependency-Check to use the NVD API.
      # When absent, the build will skip the dependency check to avoid NVD 403s.
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build and test
        working-directory: openapi-jsonschema-java
        shell: bash
        run: |
          if [[ -n "$NVD_API_KEY" ]]; then
            echo "NVD_API_KEY present: running full verify with OWASP Dependency-Check"
            mvn -B clean verify -Dnvd.api.key="$NVD_API_KEY"
          else
            echo "NVD_API_KEY not set: skipping OWASP Dependency-Check"
            mvn -B -Ddependency-check.skip=true clean verify
          fi

      - name: Static analysis
        working-directory: openapi-jsonschema-java
        run: mvn -B checkstyle:check spotbugs:check pmd:check

      - name: Coverage gate
        working-directory: openapi-jsonschema-java
        run: mvn -B jacoco:check
