name: Quality Gate

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build and test
        working-directory: openapi-jsonschema-java
        run: mvn -B clean verify

      - name: Static analysis
        working-directory: openapi-jsonschema-java
        run: mvn -B checkstyle:check spotbugs:check pmd:check

      - name: Coverage gate
        working-directory: openapi-jsonschema-java
        run: mvn -B jacoco:check

